# theme: jekyll-theme-minimal
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            Nabla Containers
tagline:          'Strong Isolation through Kernel Surface Reduction'
description:      'A blog about Security, Containers and OS'
url:              https://nabla-containers.github.io
baseurl:          /

author:
  name:           'TBD'
  url:            https://twitter.com/

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/nabla-containers
